var csv = d3.csv("../asset/data/code_list.csv")

csv.then(function(data) {
    console.log(data)

    var fun_sub = d3.select('#fun_sub')
    fun_sub.selectAll("div")
           .data(data)
           .enter()
           .filter(d => d.sub == "fun_sub")
           .append("div")
           .attr("id", "sub_item")
           .append("h2")
           .text(d => d.title)
    
    var learn_sub = d3.select('#learn_sub')
    learn_sub.selectAll("div")
             .data(data)
             .enter()
             .filter(d => d.sub == "learn_sub")
             .append("div")
             .attr("id", "sub_item")
             .append("h2")
             .text(d => d.title)
    
    var work_sub = d3.select('#work_sub')
    work_sub.selectAll("div")
            .data(data)
            .enter()
            .filter(d => d.sub == "work_sub")
            .append("div")
            .attr("id", "sub_item")
            .append("h2")
            .text(d => d.title)
    
    var sub_description = d3.selectAll("#sub_item")
    sub_description.data(data)
                   .append("p")
                   .attr("id", "sub_item_description")
                   .text(d => d.description)
    var sub_link = d3.selectAll("#sub_item_description")
                     .data(data)
                     .filter(d => d.link.includes("http"))
                     .append("a")
                     .attr("href", d => d.link)
                     .text("here ")
                     .attr("target", "_blank")
                     .attr("class", "fun_item_link")
})